/** Generated by itemis CREATE code generator. */


#include "../src/sc_types.h"

#include "assignment3.h"

/*! \file
Implementation of the state machine 'assignment3'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_region_Idle(Assignment3* handle);
static void enact_main_region_Dispense(Assignment3* handle);
static void enact_main_region_Return_Credit(Assignment3* handle);
static void enseq_main_region_Idle_default(Assignment3* handle);
static void enseq_main_region_Dispense_default(Assignment3* handle);
static void enseq_main_region_Return_Credit_default(Assignment3* handle);
static void enseq_main_region_default(Assignment3* handle);
static void exseq_main_region_Idle(Assignment3* handle);
static void exseq_main_region_Dispense(Assignment3* handle);
static void exseq_main_region_Return_Credit(Assignment3* handle);
static void exseq_main_region(Assignment3* handle);
static void react_main_region__entry_Default(Assignment3* handle);

/*! State machine reactions. */
static sc_integer react(Assignment3* handle, const sc_integer transitioned_before);

/*! The reactions of state Idle. */
static sc_integer main_region_Idle_react(Assignment3* handle, const sc_integer transitioned_before);

/*! The reactions of state Dispense. */
static sc_integer main_region_Dispense_react(Assignment3* handle, const sc_integer transitioned_before);

/*! The reactions of state Return Credit. */
static sc_integer main_region_Return_Credit_react(Assignment3* handle, const sc_integer transitioned_before);


static void clear_in_events(Assignment3* handle);

static void micro_step(Assignment3* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Assignment3* handle);




static void assignment3_internal_set_credit(Assignment3* handle, sc_integer value)
;
static void assignment3_internal_set_product(Assignment3* handle, sc_integer value)
;
static void assignment3_internal_set_price(Assignment3* handle, sc_integer value)
;


static void assignment3_eventqueue_init(assignment3_eventqueue * eq, assignment3_event *buffer, sc_integer capacity);
static sc_integer assignment3_eventqueue_size(assignment3_eventqueue * eq);
static void assignment3_event_init(assignment3_event * ev, Assignment3EventID name);
static assignment3_event assignment3_eventqueue_pop(assignment3_eventqueue * eq);
static sc_boolean assignment3_eventqueue_push(assignment3_eventqueue * eq, assignment3_event ev);
static void assignment3_add_event_to_queue(assignment3_eventqueue * eq, Assignment3EventID name);
static sc_boolean assignment3_dispatch_event(Assignment3* handle, const assignment3_event * event);
static assignment3_event assignment3_get_next_event(Assignment3* handle);
static sc_boolean assignment3_dispatch_next_event(Assignment3* handle);


void assignment3_init(Assignment3* handle)
{
	sc_integer i;
	
	for (i = 0; i < ASSIGNMENT3_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Assignment3_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart assignment3 */
	assignment3_internal_set_credit(handle, 0);
	assignment3_internal_set_product(handle, 0);
	assignment3_internal_set_price(handle, 0);
	assignment3_led1_set_power(handle, 0);
	assignment3_led2_set_power(handle, 0);
	assignment3_led3_set_power(handle, 0);
	assignment3_led4_set_power(handle, 0);
	
	handle->isExecuting = bool_false;
	assignment3_eventqueue_init(&handle->in_event_queue, handle->in_buffer, ASSIGNMENT3_IN_EVENTQUEUE_BUFFERSIZE);
}

void assignment3_enter(Assignment3* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart assignment3 */
	enseq_main_region_default(handle);
	handle->isExecuting = bool_false;
}

void assignment3_exit(Assignment3* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart assignment3 */
	exseq_main_region(handle);
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void assignment3_trigger_without_event(Assignment3* handle) {
	run_cycle(handle);
}


sc_boolean assignment3_is_active(const Assignment3* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < ASSIGNMENT3_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Assignment3_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean assignment3_is_final(const Assignment3* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean assignment3_is_state_active(const Assignment3* handle, Assignment3States state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Assignment3_main_region_Idle :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ASSIGNMENT3_MAIN_REGION_IDLE] == Assignment3_main_region_Idle
			);
				break;
		case Assignment3_main_region_Dispense :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ASSIGNMENT3_MAIN_REGION_DISPENSE] == Assignment3_main_region_Dispense
			);
				break;
		case Assignment3_main_region_Return_Credit :
			result = (sc_boolean) (handle->stateConfVector[SCVI_ASSIGNMENT3_MAIN_REGION_RETURN_CREDIT] == Assignment3_main_region_Return_Credit
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(Assignment3* handle)
{
	handle->ifaceBut1.Insert_raised = bool_false;
	handle->ifaceBut2.Insert_raised = bool_false;
	handle->ifaceBut3.Browse_raised = bool_false;
	handle->ifaceBut4.Enter_raised = bool_false;
}

static void micro_step(Assignment3* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Assignment3_main_region_Idle :
		{
			main_region_Idle_react(handle,-1);
			break;
		}
		case Assignment3_main_region_Dispense :
		{
			main_region_Dispense_react(handle,-1);
			break;
		}
		case Assignment3_main_region_Return_Credit :
		{
			main_region_Return_Credit_react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

static void run_cycle(Assignment3* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	assignment3_dispatch_next_event(handle);
	do
	{ 
		micro_step(handle);
		clear_in_events(handle);
	} while (assignment3_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}


void assignment3_but1_raise_insert(Assignment3* handle)
{
	assignment3_add_event_to_queue(&(handle->in_event_queue), Assignment3_but1_Insert);
	run_cycle(handle);
}



void assignment3_but2_raise_insert(Assignment3* handle)
{
	assignment3_add_event_to_queue(&(handle->in_event_queue), Assignment3_but2_Insert);
	run_cycle(handle);
}



void assignment3_but3_raise_browse(Assignment3* handle)
{
	assignment3_add_event_to_queue(&(handle->in_event_queue), Assignment3_but3_Browse);
	run_cycle(handle);
}



void assignment3_but4_raise_enter(Assignment3* handle)
{
	assignment3_add_event_to_queue(&(handle->in_event_queue), Assignment3_but4_Enter);
	run_cycle(handle);
}





sc_integer assignment3_led1_get_power(const Assignment3* handle)
{
	return handle->ifaceLed1.Power;
}
void assignment3_led1_set_power(Assignment3* handle, sc_integer value)
{
	handle->ifaceLed1.Power = value;
}


sc_integer assignment3_led2_get_power(const Assignment3* handle)
{
	return handle->ifaceLed2.Power;
}
void assignment3_led2_set_power(Assignment3* handle, sc_integer value)
{
	handle->ifaceLed2.Power = value;
}


sc_integer assignment3_led3_get_power(const Assignment3* handle)
{
	return handle->ifaceLed3.Power;
}
void assignment3_led3_set_power(Assignment3* handle, sc_integer value)
{
	handle->ifaceLed3.Power = value;
}


sc_integer assignment3_led4_get_power(const Assignment3* handle)
{
	return handle->ifaceLed4.Power;
}
void assignment3_led4_set_power(Assignment3* handle, sc_integer value)
{
	handle->ifaceLed4.Power = value;
}

static void assignment3_internal_set_credit(Assignment3* handle, sc_integer value)
{
	handle->internal.Credit = value;
}
static void assignment3_internal_set_product(Assignment3* handle, sc_integer value)
{
	handle->internal.Product = value;
}
static void assignment3_internal_set_price(Assignment3* handle, sc_integer value)
{
	handle->internal.Price = value;
}


/* implementations of all internal functions */

/* Entry action for state 'Idle'. */
static void enact_main_region_Idle(Assignment3* handle)
{
	/* Entry action for state 'Idle'. */
	if ((handle->internal.Product) == (0))
	{ 
		assignment3_led1_set_power(handle, 0);
		assignment3_led2_set_power(handle, 0);
		assignment3_internal_set_price(handle, 0);
	} 
	if ((handle->internal.Product) == (1))
	{ 
		assignment3_led1_set_power(handle, 0);
		assignment3_led2_set_power(handle, 1);
		assignment3_internal_set_price(handle, 1);
	} 
	if ((handle->internal.Product) == (2))
	{ 
		assignment3_led1_set_power(handle, 1);
		assignment3_led2_set_power(handle, 0);
		assignment3_internal_set_price(handle, 2);
	} 
	if ((handle->internal.Product) == (3))
	{ 
		assignment3_led1_set_power(handle, 1);
		assignment3_led2_set_power(handle, 1);
		assignment3_internal_set_price(handle, 3);
	} 
}

/* Entry action for state 'Dispense'. */
static void enact_main_region_Dispense(Assignment3* handle)
{
	/* Entry action for state 'Dispense'. */
	if ((handle->internal.Credit) >= (handle->internal.Price))
	{ 
		assignment3_led3_set_power(handle, 1);
	} 
	if ((handle->internal.Credit) < (handle->internal.Price))
	{ 
		assignment3_led3_set_power(handle, 0);
	} 
}

/* Entry action for state 'Return Credit'. */
static void enact_main_region_Return_Credit(Assignment3* handle)
{
	/* Entry action for state 'Return Credit'. */
	if ((handle->internal.Credit) > (0))
	{ 
		assignment3_led4_set_power(handle, 1);
	} 
	if ((handle->internal.Credit) <= (0))
	{ 
		assignment3_led4_set_power(handle, 0);
	} 
}

/* 'default' enter sequence for state Idle */
static void enseq_main_region_Idle_default(Assignment3* handle)
{
	/* 'default' enter sequence for state Idle */
	enact_main_region_Idle(handle);
	handle->stateConfVector[0] = Assignment3_main_region_Idle;
}

/* 'default' enter sequence for state Dispense */
static void enseq_main_region_Dispense_default(Assignment3* handle)
{
	/* 'default' enter sequence for state Dispense */
	enact_main_region_Dispense(handle);
	handle->stateConfVector[0] = Assignment3_main_region_Dispense;
}

/* 'default' enter sequence for state Return Credit */
static void enseq_main_region_Return_Credit_default(Assignment3* handle)
{
	/* 'default' enter sequence for state Return Credit */
	enact_main_region_Return_Credit(handle);
	handle->stateConfVector[0] = Assignment3_main_region_Return_Credit;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Assignment3* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state Idle */
static void exseq_main_region_Idle(Assignment3* handle)
{
	/* Default exit sequence for state Idle */
	handle->stateConfVector[0] = Assignment3_last_state;
}

/* Default exit sequence for state Dispense */
static void exseq_main_region_Dispense(Assignment3* handle)
{
	/* Default exit sequence for state Dispense */
	handle->stateConfVector[0] = Assignment3_last_state;
}

/* Default exit sequence for state Return Credit */
static void exseq_main_region_Return_Credit(Assignment3* handle)
{
	/* Default exit sequence for state Return Credit */
	handle->stateConfVector[0] = Assignment3_last_state;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Assignment3* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of assignment3.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Assignment3_main_region_Idle :
		{
			exseq_main_region_Idle(handle);
			break;
		}
		case Assignment3_main_region_Dispense :
		{
			exseq_main_region_Dispense(handle);
			break;
		}
		case Assignment3_main_region_Return_Credit :
		{
			exseq_main_region_Return_Credit(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Assignment3* handle)
{
	/* Default react sequence for initial entry  */
	assignment3_internal_set_credit(handle, 0);
	assignment3_internal_set_product(handle, 0);
	enseq_main_region_Idle_default(handle);
}


static sc_integer react(Assignment3* handle, const sc_integer transitioned_before)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return transitioned_before;
}

static sc_integer main_region_Idle_react(Assignment3* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Idle. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->ifaceBut1.Insert_raised == bool_true)
		{ 
			exseq_main_region_Idle(handle);
			handle->internal.Credit++;
			enseq_main_region_Idle_default(handle);
			react(handle,0);
			transitioned_after = 0;
		}  else
		{
			if (handle->ifaceBut2.Insert_raised == bool_true)
			{ 
				exseq_main_region_Idle(handle);
				assignment3_internal_set_credit(handle, handle->internal.Credit + 2);
				enseq_main_region_Idle_default(handle);
				react(handle,0);
				transitioned_after = 0;
			}  else
			{
				if (((handle->ifaceBut3.Browse_raised) == bool_true) && (((handle->internal.Product) < (3)) == bool_true))
				{ 
					exseq_main_region_Idle(handle);
					handle->internal.Product++;
					enseq_main_region_Idle_default(handle);
					react(handle,0);
					transitioned_after = 0;
				}  else
				{
					if (((handle->ifaceBut3.Browse_raised) == bool_true) && (((handle->internal.Product) == (3)) == bool_true))
					{ 
						exseq_main_region_Idle(handle);
						assignment3_internal_set_product(handle, 0);
						enseq_main_region_Idle_default(handle);
						react(handle,0);
						transitioned_after = 0;
					}  else
					{
						if (((handle->ifaceBut4.Enter_raised) == bool_true) && (((handle->internal.Product) > (0)) == bool_true))
						{ 
							exseq_main_region_Idle(handle);
							enseq_main_region_Dispense_default(handle);
							react(handle,0);
							transitioned_after = 0;
						}  else
						{
							if (((handle->ifaceBut4.Enter_raised) == bool_true) && (((handle->internal.Product) == (0)) == bool_true))
							{ 
								exseq_main_region_Idle(handle);
								enseq_main_region_Return_Credit_default(handle);
								react(handle,0);
								transitioned_after = 0;
							} 
						}
					}
				}
			}
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(handle,transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer main_region_Dispense_react(Assignment3* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Dispense. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (((handle->ifaceBut4.Enter_raised) == bool_true) && (((handle->ifaceLed3.Power) == (1)) == bool_true))
		{ 
			exseq_main_region_Dispense(handle);
			assignment3_internal_set_credit(handle, handle->internal.Credit - handle->internal.Price);
			assignment3_led3_set_power(handle, 0);
			enseq_main_region_Idle_default(handle);
			react(handle,0);
			transitioned_after = 0;
		}  else
		{
			if (((handle->ifaceBut4.Enter_raised) == bool_true) && (((handle->ifaceLed3.Power) == (0)) == bool_true))
			{ 
				exseq_main_region_Dispense(handle);
				enseq_main_region_Idle_default(handle);
				react(handle,0);
				transitioned_after = 0;
			} 
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(handle,transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer main_region_Return_Credit_react(Assignment3* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Return Credit. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (((handle->ifaceBut4.Enter_raised) == bool_true) && (((handle->ifaceLed4.Power) == (1)) == bool_true))
		{ 
			exseq_main_region_Return_Credit(handle);
			assignment3_internal_set_credit(handle, 0);
			assignment3_led4_set_power(handle, 0);
			enseq_main_region_Idle_default(handle);
			react(handle,0);
			transitioned_after = 0;
		}  else
		{
			if (((handle->ifaceBut4.Enter_raised) == bool_true) && (((handle->ifaceLed4.Power) == (0)) == bool_true))
			{ 
				exseq_main_region_Return_Credit(handle);
				enseq_main_region_Idle_default(handle);
				react(handle,0);
				transitioned_after = 0;
			} 
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(handle,transitioned_before);
	} 
	return transitioned_after;
}




static void assignment3_eventqueue_init(assignment3_eventqueue * eq, assignment3_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer assignment3_eventqueue_size(assignment3_eventqueue * eq)
{
	return eq->size;
}

static assignment3_event assignment3_eventqueue_pop(assignment3_eventqueue * eq)
{
	assignment3_event event;
	if(assignment3_eventqueue_size(eq) <= 0) {
		assignment3_event_init(&event, Assignment3_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean assignment3_eventqueue_push(assignment3_eventqueue * eq, assignment3_event ev)
{
	if(assignment3_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void assignment3_event_init(assignment3_event * ev, Assignment3EventID name)
{
	ev->name = name;
}

static void assignment3_add_event_to_queue(assignment3_eventqueue * eq, Assignment3EventID name)
{
	assignment3_event event;
	assignment3_event_init(&event, name);
	assignment3_eventqueue_push(eq, event);
}

static sc_boolean assignment3_dispatch_event(Assignment3* handle, const assignment3_event * event) {
	switch(event->name) {
		case Assignment3_but1_Insert:
		{
			handle->ifaceBut1.Insert_raised = bool_true;
			return bool_true;
		}
		case Assignment3_but2_Insert:
		{
			handle->ifaceBut2.Insert_raised = bool_true;
			return bool_true;
		}
		case Assignment3_but3_Browse:
		{
			handle->ifaceBut3.Browse_raised = bool_true;
			return bool_true;
		}
		case Assignment3_but4_Enter:
		{
			handle->ifaceBut4.Enter_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static assignment3_event assignment3_get_next_event(Assignment3* handle)
{
	assignment3_event next_event;
	assignment3_event_init(&next_event, Assignment3_invalid_event);
	if(assignment3_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = assignment3_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean assignment3_dispatch_next_event(Assignment3* handle)
{
	assignment3_event nextEvent;
	nextEvent = assignment3_get_next_event(handle);
	return assignment3_dispatch_event(handle, &nextEvent);
}
