/** Generated by itemis CREATE code generator. */


#include "../src/sc_types.h"

#include "VendingMachine.h"

/*! \file
Implementation of the state machine 'VendingMachine'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_region_Idle(VendingMachine* handle);
static void enact_main_region_Dispense(VendingMachine* handle);
static void enact_main_region_Return_Credit(VendingMachine* handle);
static void enseq_main_region_Idle_default(VendingMachine* handle);
static void enseq_main_region_Dispense_default(VendingMachine* handle);
static void enseq_main_region_Return_Credit_default(VendingMachine* handle);
static void enseq_main_region_default(VendingMachine* handle);
static void exseq_main_region_Idle(VendingMachine* handle);
static void exseq_main_region_Dispense(VendingMachine* handle);
static void exseq_main_region_Return_Credit(VendingMachine* handle);
static void exseq_main_region(VendingMachine* handle);
static void react_main_region__entry_Default(VendingMachine* handle);

/*! State machine reactions. */
static sc_integer react(VendingMachine* handle, const sc_integer transitioned_before);

/*! The reactions of state Idle. */
static sc_integer main_region_Idle_react(VendingMachine* handle, const sc_integer transitioned_before);

/*! The reactions of state Dispense. */
static sc_integer main_region_Dispense_react(VendingMachine* handle, const sc_integer transitioned_before);

/*! The reactions of state Return Credit. */
static sc_integer main_region_Return_Credit_react(VendingMachine* handle, const sc_integer transitioned_before);


static void clear_in_events(VendingMachine* handle);

static void micro_step(VendingMachine* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(VendingMachine* handle);




static void vendingMachine_internal_set_credit(VendingMachine* handle, sc_integer value)
;
static void vendingMachine_internal_set_product(VendingMachine* handle, sc_integer value)
;
static void vendingMachine_internal_set_price(VendingMachine* handle, sc_integer value)
;


static void vendingmachine_eventqueue_init(vendingmachine_eventqueue * eq, vendingmachine_event *buffer, sc_integer capacity);
static sc_integer vendingmachine_eventqueue_size(vendingmachine_eventqueue * eq);
static void vendingmachine_event_init(vendingmachine_event * ev, VendingMachineEventID name);
static vendingmachine_event vendingmachine_eventqueue_pop(vendingmachine_eventqueue * eq);
static sc_boolean vendingmachine_eventqueue_push(vendingmachine_eventqueue * eq, vendingmachine_event ev);
static void vendingMachine_add_event_to_queue(vendingmachine_eventqueue * eq, VendingMachineEventID name);
static sc_boolean vendingMachine_dispatch_event(VendingMachine* handle, const vendingmachine_event * event);
static vendingmachine_event vendingMachine_get_next_event(VendingMachine* handle);
static sc_boolean vendingMachine_dispatch_next_event(VendingMachine* handle);


void vendingMachine_init(VendingMachine* handle)
{
	sc_integer i;
	
	for (i = 0; i < VENDINGMACHINE_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = VendingMachine_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart VendingMachine */
	vendingMachine_internal_set_credit(handle, 0);
	vendingMachine_internal_set_product(handle, 0);
	vendingMachine_internal_set_price(handle, 0);
	vendingMachine_led1_set_power(handle, 0);
	vendingMachine_led2_set_power(handle, 0);
	vendingMachine_led3_set_power(handle, 0);
	vendingMachine_led4_set_power(handle, 0);
	
	handle->isExecuting = bool_false;
	vendingmachine_eventqueue_init(&handle->in_event_queue, handle->in_buffer, VENDINGMACHINE_IN_EVENTQUEUE_BUFFERSIZE);
}

void vendingMachine_enter(VendingMachine* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart VendingMachine */
	enseq_main_region_default(handle);
	handle->isExecuting = bool_false;
}

void vendingMachine_exit(VendingMachine* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart VendingMachine */
	exseq_main_region(handle);
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void vendingMachine_trigger_without_event(VendingMachine* handle) {
	run_cycle(handle);
}


sc_boolean vendingMachine_is_active(const VendingMachine* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < VENDINGMACHINE_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != VendingMachine_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean vendingMachine_is_final(const VendingMachine* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean vendingMachine_is_state_active(const VendingMachine* handle, VendingMachineStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case VendingMachine_main_region_Idle :
			result = (sc_boolean) (handle->stateConfVector[SCVI_VENDINGMACHINE_MAIN_REGION_IDLE] == VendingMachine_main_region_Idle
			);
				break;
		case VendingMachine_main_region_Dispense :
			result = (sc_boolean) (handle->stateConfVector[SCVI_VENDINGMACHINE_MAIN_REGION_DISPENSE] == VendingMachine_main_region_Dispense
			);
				break;
		case VendingMachine_main_region_Return_Credit :
			result = (sc_boolean) (handle->stateConfVector[SCVI_VENDINGMACHINE_MAIN_REGION_RETURN_CREDIT] == VendingMachine_main_region_Return_Credit
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(VendingMachine* handle)
{
	handle->ifaceBut1.Insert_raised = bool_false;
	handle->ifaceBut2.Insert_raised = bool_false;
	handle->ifaceBut3.Browse_raised = bool_false;
	handle->ifaceBut4.Enter_raised = bool_false;
}

static void micro_step(VendingMachine* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case VendingMachine_main_region_Idle :
		{
			main_region_Idle_react(handle,-1);
			break;
		}
		case VendingMachine_main_region_Dispense :
		{
			main_region_Dispense_react(handle,-1);
			break;
		}
		case VendingMachine_main_region_Return_Credit :
		{
			main_region_Return_Credit_react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

static void run_cycle(VendingMachine* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	vendingMachine_dispatch_next_event(handle);
	do
	{ 
		micro_step(handle);
		clear_in_events(handle);
	} while (vendingMachine_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}


void vendingMachine_but1_raise_insert(VendingMachine* handle)
{
	vendingMachine_add_event_to_queue(&(handle->in_event_queue), VendingMachine_but1_Insert);
	run_cycle(handle);
}



void vendingMachine_but2_raise_insert(VendingMachine* handle)
{
	vendingMachine_add_event_to_queue(&(handle->in_event_queue), VendingMachine_but2_Insert);
	run_cycle(handle);
}



void vendingMachine_but3_raise_browse(VendingMachine* handle)
{
	vendingMachine_add_event_to_queue(&(handle->in_event_queue), VendingMachine_but3_Browse);
	run_cycle(handle);
}



void vendingMachine_but4_raise_enter(VendingMachine* handle)
{
	vendingMachine_add_event_to_queue(&(handle->in_event_queue), VendingMachine_but4_Enter);
	run_cycle(handle);
}





sc_integer vendingMachine_led1_get_power(const VendingMachine* handle)
{
	return handle->ifaceLed1.Power;
}
void vendingMachine_led1_set_power(VendingMachine* handle, sc_integer value)
{
	handle->ifaceLed1.Power = value;
}


sc_integer vendingMachine_led2_get_power(const VendingMachine* handle)
{
	return handle->ifaceLed2.Power;
}
void vendingMachine_led2_set_power(VendingMachine* handle, sc_integer value)
{
	handle->ifaceLed2.Power = value;
}


sc_integer vendingMachine_led3_get_power(const VendingMachine* handle)
{
	return handle->ifaceLed3.Power;
}
void vendingMachine_led3_set_power(VendingMachine* handle, sc_integer value)
{
	handle->ifaceLed3.Power = value;
}


sc_integer vendingMachine_led4_get_power(const VendingMachine* handle)
{
	return handle->ifaceLed4.Power;
}
void vendingMachine_led4_set_power(VendingMachine* handle, sc_integer value)
{
	handle->ifaceLed4.Power = value;
}

static void vendingMachine_internal_set_credit(VendingMachine* handle, sc_integer value)
{
	handle->internal.Credit = value;
}
static void vendingMachine_internal_set_product(VendingMachine* handle, sc_integer value)
{
	handle->internal.Product = value;
}
static void vendingMachine_internal_set_price(VendingMachine* handle, sc_integer value)
{
	handle->internal.Price = value;
}


/* implementations of all internal functions */

/* Entry action for state 'Idle'. */
static void enact_main_region_Idle(VendingMachine* handle)
{
	/* Entry action for state 'Idle'. */
	if ((handle->internal.Product) == (0))
	{ 
		vendingMachine_led1_set_power(handle, 0);
		vendingMachine_led2_set_power(handle, 0);
		vendingMachine_internal_set_price(handle, 0);
	} 
	if ((handle->internal.Product) == (1))
	{ 
		vendingMachine_led1_set_power(handle, 0);
		vendingMachine_led2_set_power(handle, 1);
		vendingMachine_internal_set_price(handle, 1);
	} 
	if ((handle->internal.Product) == (2))
	{ 
		vendingMachine_led1_set_power(handle, 1);
		vendingMachine_led2_set_power(handle, 0);
		vendingMachine_internal_set_price(handle, 2);
	} 
	if ((handle->internal.Product) == (3))
	{ 
		vendingMachine_led1_set_power(handle, 1);
		vendingMachine_led2_set_power(handle, 1);
		vendingMachine_internal_set_price(handle, 3);
	} 
}

/* Entry action for state 'Dispense'. */
static void enact_main_region_Dispense(VendingMachine* handle)
{
	/* Entry action for state 'Dispense'. */
	if ((handle->internal.Credit) >= (handle->internal.Price))
	{ 
		vendingMachine_led3_set_power(handle, 1);
	} 
	if ((handle->internal.Credit) < (handle->internal.Price))
	{ 
		vendingMachine_led3_set_power(handle, 0);
	} 
}

/* Entry action for state 'Return Credit'. */
static void enact_main_region_Return_Credit(VendingMachine* handle)
{
	/* Entry action for state 'Return Credit'. */
	if ((handle->internal.Credit) > (0))
	{ 
		vendingMachine_led4_set_power(handle, 1);
	} 
	if ((handle->internal.Credit) <= (0))
	{ 
		vendingMachine_led4_set_power(handle, 0);
	} 
}

/* 'default' enter sequence for state Idle */
static void enseq_main_region_Idle_default(VendingMachine* handle)
{
	/* 'default' enter sequence for state Idle */
	enact_main_region_Idle(handle);
	handle->stateConfVector[0] = VendingMachine_main_region_Idle;
}

/* 'default' enter sequence for state Dispense */
static void enseq_main_region_Dispense_default(VendingMachine* handle)
{
	/* 'default' enter sequence for state Dispense */
	enact_main_region_Dispense(handle);
	handle->stateConfVector[0] = VendingMachine_main_region_Dispense;
}

/* 'default' enter sequence for state Return Credit */
static void enseq_main_region_Return_Credit_default(VendingMachine* handle)
{
	/* 'default' enter sequence for state Return Credit */
	enact_main_region_Return_Credit(handle);
	handle->stateConfVector[0] = VendingMachine_main_region_Return_Credit;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(VendingMachine* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state Idle */
static void exseq_main_region_Idle(VendingMachine* handle)
{
	/* Default exit sequence for state Idle */
	handle->stateConfVector[0] = VendingMachine_last_state;
}

/* Default exit sequence for state Dispense */
static void exseq_main_region_Dispense(VendingMachine* handle)
{
	/* Default exit sequence for state Dispense */
	handle->stateConfVector[0] = VendingMachine_last_state;
}

/* Default exit sequence for state Return Credit */
static void exseq_main_region_Return_Credit(VendingMachine* handle)
{
	/* Default exit sequence for state Return Credit */
	handle->stateConfVector[0] = VendingMachine_last_state;
}

/* Default exit sequence for region main region */
static void exseq_main_region(VendingMachine* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of VendingMachine.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case VendingMachine_main_region_Idle :
		{
			exseq_main_region_Idle(handle);
			break;
		}
		case VendingMachine_main_region_Dispense :
		{
			exseq_main_region_Dispense(handle);
			break;
		}
		case VendingMachine_main_region_Return_Credit :
		{
			exseq_main_region_Return_Credit(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(VendingMachine* handle)
{
	/* Default react sequence for initial entry  */
	vendingMachine_internal_set_credit(handle, 0);
	vendingMachine_internal_set_product(handle, 0);
	enseq_main_region_Idle_default(handle);
}


static sc_integer react(VendingMachine* handle, const sc_integer transitioned_before)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return transitioned_before;
}

static sc_integer main_region_Idle_react(VendingMachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Idle. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->ifaceBut1.Insert_raised == bool_true)
		{ 
			exseq_main_region_Idle(handle);
			handle->internal.Credit++;
			enseq_main_region_Idle_default(handle);
			react(handle,0);
			transitioned_after = 0;
		}  else
		{
			if (handle->ifaceBut2.Insert_raised == bool_true)
			{ 
				exseq_main_region_Idle(handle);
				vendingMachine_internal_set_credit(handle, handle->internal.Credit + 2);
				enseq_main_region_Idle_default(handle);
				react(handle,0);
				transitioned_after = 0;
			}  else
			{
				if (((handle->ifaceBut3.Browse_raised) == bool_true) && (((handle->internal.Product) < (3)) == bool_true))
				{ 
					exseq_main_region_Idle(handle);
					handle->internal.Product++;
					enseq_main_region_Idle_default(handle);
					react(handle,0);
					transitioned_after = 0;
				}  else
				{
					if (((handle->ifaceBut3.Browse_raised) == bool_true) && (((handle->internal.Product) == (3)) == bool_true))
					{ 
						exseq_main_region_Idle(handle);
						vendingMachine_internal_set_product(handle, 0);
						enseq_main_region_Idle_default(handle);
						react(handle,0);
						transitioned_after = 0;
					}  else
					{
						if (((handle->ifaceBut4.Enter_raised) == bool_true) && (((handle->internal.Product) > (0)) == bool_true))
						{ 
							exseq_main_region_Idle(handle);
							enseq_main_region_Dispense_default(handle);
							react(handle,0);
							transitioned_after = 0;
						}  else
						{
							if (((handle->ifaceBut4.Enter_raised) == bool_true) && (((handle->internal.Product) == (0)) == bool_true))
							{ 
								exseq_main_region_Idle(handle);
								enseq_main_region_Return_Credit_default(handle);
								react(handle,0);
								transitioned_after = 0;
							} 
						}
					}
				}
			}
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(handle,transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer main_region_Dispense_react(VendingMachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Dispense. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (((handle->ifaceBut4.Enter_raised) == bool_true) && (((handle->ifaceLed3.Power) == (1)) == bool_true))
		{ 
			exseq_main_region_Dispense(handle);
			vendingMachine_internal_set_credit(handle, handle->internal.Credit - handle->internal.Price);
			vendingMachine_led3_set_power(handle, 0);
			enseq_main_region_Idle_default(handle);
			react(handle,0);
			transitioned_after = 0;
		}  else
		{
			if (((handle->ifaceBut4.Enter_raised) == bool_true) && (((handle->ifaceLed3.Power) == (0)) == bool_true))
			{ 
				exseq_main_region_Dispense(handle);
				enseq_main_region_Idle_default(handle);
				react(handle,0);
				transitioned_after = 0;
			} 
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(handle,transitioned_before);
	} 
	return transitioned_after;
}

static sc_integer main_region_Return_Credit_react(VendingMachine* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Return Credit. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (((handle->ifaceBut4.Enter_raised) == bool_true) && (((handle->ifaceLed4.Power) == (1)) == bool_true))
		{ 
			exseq_main_region_Return_Credit(handle);
			vendingMachine_internal_set_credit(handle, 0);
			vendingMachine_led4_set_power(handle, 0);
			enseq_main_region_Idle_default(handle);
			react(handle,0);
			transitioned_after = 0;
		}  else
		{
			if (((handle->ifaceBut4.Enter_raised) == bool_true) && (((handle->ifaceLed4.Power) == (0)) == bool_true))
			{ 
				exseq_main_region_Return_Credit(handle);
				enseq_main_region_Idle_default(handle);
				react(handle,0);
				transitioned_after = 0;
			} 
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(handle,transitioned_before);
	} 
	return transitioned_after;
}




static void vendingmachine_eventqueue_init(vendingmachine_eventqueue * eq, vendingmachine_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer vendingmachine_eventqueue_size(vendingmachine_eventqueue * eq)
{
	return eq->size;
}

static vendingmachine_event vendingmachine_eventqueue_pop(vendingmachine_eventqueue * eq)
{
	vendingmachine_event event;
	if(vendingmachine_eventqueue_size(eq) <= 0) {
		vendingmachine_event_init(&event, VendingMachine_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean vendingmachine_eventqueue_push(vendingmachine_eventqueue * eq, vendingmachine_event ev)
{
	if(vendingmachine_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void vendingmachine_event_init(vendingmachine_event * ev, VendingMachineEventID name)
{
	ev->name = name;
}

static void vendingMachine_add_event_to_queue(vendingmachine_eventqueue * eq, VendingMachineEventID name)
{
	vendingmachine_event event;
	vendingmachine_event_init(&event, name);
	vendingmachine_eventqueue_push(eq, event);
}

static sc_boolean vendingMachine_dispatch_event(VendingMachine* handle, const vendingmachine_event * event) {
	switch(event->name) {
		case VendingMachine_but1_Insert:
		{
			handle->ifaceBut1.Insert_raised = bool_true;
			return bool_true;
		}
		case VendingMachine_but2_Insert:
		{
			handle->ifaceBut2.Insert_raised = bool_true;
			return bool_true;
		}
		case VendingMachine_but3_Browse:
		{
			handle->ifaceBut3.Browse_raised = bool_true;
			return bool_true;
		}
		case VendingMachine_but4_Enter:
		{
			handle->ifaceBut4.Enter_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static vendingmachine_event vendingMachine_get_next_event(VendingMachine* handle)
{
	vendingmachine_event next_event;
	vendingmachine_event_init(&next_event, VendingMachine_invalid_event);
	if(vendingmachine_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = vendingmachine_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean vendingMachine_dispatch_next_event(VendingMachine* handle)
{
	vendingmachine_event nextEvent;
	nextEvent = vendingMachine_get_next_event(handle);
	return vendingMachine_dispatch_event(handle, &nextEvent);
}